idf_component_register(
   SRCS 
      "app/rtos_ble_led.c" 
      "ble/ble_telemetry.c"
      "dsp/audio_buffer.c" 
      "dsp/fft_engine.c"
      "dsp/spectrum_map.c" 
      "dsp/audio_dsp_pipeline.c" 
      "led/effects/led_effects.c"
      "led/effects/led_color_fade.c"
      "led/led_matrix_renderer.c"
      "led/led_cube_mapper.c"
      "led/led_cube_renderer.c"
      "led/led_controller.c"
      "led/led_cube.c"
      "led/effects/led_effect_pockets.c"
      "test/self_test.c" 
      "test/gpio4_scope_test.c"
      "common/app_log.c"
      "common/random_utils.c"
   INCLUDE_DIRS 
      "."
      "app"
      "ble"
      "dsp"
      "led"
      "test"
      "common"
      "led/effects"
   REQUIRES led_strip
   PRIV_REQUIRES esp_driver_gpio esp_driver_i2s bt nvs_flash)
